{{- if .Values.dockerHosts.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "coolify-platform.vmNamespace" . }}
  labels:
    {{- include "coolify-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: vm-namespace
    coolify.io/managed: "true"
{{- end }}
